version: '3'

services:
  sde_db:
    image: postgres:16.1-alpine3.18
    container_name: sde_db
    environment:
      POSTGRES_DB: sde
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
    volumes:
      - ./database/sde_db:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  app_db:
    image: postgres:16.1-alpine3.18
    container_name: app_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
    volumes:
      - ./database/app_db:/var/lib/postgresql/data
    ports:
      - "54322:5432"
